services:
  - type: web
    name: flask-mysql-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: root123
      - key: DB_NAME
        value: atliq_tshirts
